# Generated by Django 4.1.2 on 2022-11-01 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 7, 11, 58, 119118, tzinfo=datetime.timezone.utc)),
        ),
    ]
